"""First commit

Revision ID: 418e07c77e60
Revises: 
Create Date: 2021-04-29 01:06:42.481761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418e07c77e60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('payout_id', sa.Integer(), nullable=True),
    sa.Column('external_reference_id', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('memo', sa.String(length=300), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('is_dispute', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payout_id'], ['payout.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payable_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('external_reference_id', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payable_id'], ['payable.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('payable_id', sa.Integer(), nullable=True),
    sa.Column('normal_pay', sa.Float(), nullable=True),
    sa.Column('special_pay', sa.Float(), nullable=True),
    sa.Column('special_units', sa.Integer(), nullable=True),
    sa.Column('special_explanation', sa.String(length=300), nullable=True),
    sa.Column('shift_start', sa.String(length=5), nullable=True),
    sa.Column('lunch_start', sa.String(length=5), nullable=True),
    sa.Column('lunch_end', sa.String(length=5), nullable=True),
    sa.Column('shift_end', sa.String(length=5), nullable=True),
    sa.Column('is_cancel', sa.Boolean(), nullable=True),
    sa.Column('is_waitlist', sa.Boolean(), nullable=True),
    sa.Column('is_noshow', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['payable_id'], ['payable.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('shift_start', sa.DateTime(), nullable=True),
    sa.Column('shift_end', sa.DateTime(), nullable=True),
    sa.Column('street_address', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=5), nullable=True),
    sa.Column('skilled_capacity', sa.Integer(), nullable=True),
    sa.Column('unskilled_capacity', sa.Integer(), nullable=True),
    sa.Column('advance_url', sa.String(length=300), nullable=True),
    sa.Column('need_drug', sa.Boolean(), nullable=True),
    sa.Column('need_background', sa.Boolean(), nullable=True),
    sa.Column('skilled_base', sa.Float(), nullable=True),
    sa.Column('unskilled_base', sa.Float(), nullable=True),
    sa.Column('special_base', sa.Float(), nullable=True),
    sa.Column('special_rate', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('user_type', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=300), nullable=True),
    sa.Column('is_blacklist', sa.Boolean(), nullable=True),
    sa.Column('is_drug', sa.Boolean(), nullable=True),
    sa.Column('is_background', sa.Boolean(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('event')
    op.drop_table('shift')
    op.drop_table('region')
    op.drop_table('payout')
    op.drop_table('payable')
    # ### end Alembic commands ###
